[package]
name = "Movemate"
version = "1.0.0"
authors = ["David Lucid <david@pentagon.xyz>"]

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
movemate = "0x1bfd5627ed24905e16243bca5e339eca19e98494df5e51eb213f4865e398d569"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/move-stdlib"
rev = "3910637893b6aed4af73b19a2c429ef717e1ee26"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-stdlib"
rev = "3910637893b6aed4af73b19a2c429ef717e1ee26"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
rev = "movement"
